[tool.poetry]
name = "ecom-django"
version = "0.1.0"
description = ""
authors = ["Akhil H Nair <aklhnrpm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
